#!/usr/bin/env python
# SPDX-License-Identifier: Apache-2.0
"""Write the committed defaults to ``configs/default.yaml`` as a readable record.

The pre-registered parameters live in ``src/hsbcfraud/config.py``, because that is what
``load_config(None)`` returns and therefore what actually produced ``results/tables/``.  But
a reviewer should not have to read a Python class to find out what $\\alpha$ grid was frozen,
and both ``docs/protocol.md`` and ``scripts/check_protocol.py`` referred to
``configs/default.yaml`` for months before anything wrote to it.  The guarantee hash was
always computed from the live defaults, so the enforcement was real and only the description
was wrong -- but a documented path that does not exist is the kind of gap this project's
discipline is supposed to close, not create.

The dataclass stays the single source of truth.  This file is generated from it, and
``scripts/check_protocol.py --verify-dump`` fails if the two drift apart, so the record
cannot quietly go stale.

    .venv/bin/python scripts/dump_config.py
"""

from __future__ import annotations

import argparse
from pathlib import Path

import yaml

from hsbcfraud.config import load_config
from hsbcfraud.paths import display_path

REPO = Path(__file__).resolve().parents[1]

HEADER = """# SPDX-License-Identifier: Apache-2.0
#
# GENERATED by scripts/dump_config.py from the committed defaults in src/hsbcfraud/config.py.
# Edit the dataclass, not this file; `scripts/check_protocol.py --verify-dump` fails on drift.
#
# These are the values that produced results/tables/.  The subset the guarantees depend on is
# hashed by scripts/check_protocol.py, which refuses an undocumented change to any of them.
"""


def render(config_path: Path | None) -> str:
    dumped = load_config(config_path).model_dump()
    return HEADER + yaml.safe_dump(
        dumped, sort_keys=True, default_flow_style=False, width=96
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", type=Path, default=REPO / "configs" / "default.yaml")
    args = parser.parse_args(argv)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render(None), encoding="utf-8")
    print(f"Wrote {display_path(args.out)} from the committed defaults")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
